const LANDING_PAGE_URL = process.env.NEXT_PUBLIC_LANDING_URL
const STORE_PAGE_URL = process.env.NEXT_PUBLIC_STORE_URL
const PLATFORM_URL = process.env.NEXT_PUBLIC_PLATFORM_URL
const PLATFORM_URL_CLASSROOM = `${process.env.NEXT_PUBLIC_PLATFORM_URL}/classroom-service`
const PLATFORM_URL_CUSTOMER = `${process.env.NEXT_PUBLIC_PLATFORM_URL}/customer-service`
const USER_SERVICE = `${process.env.NEXT_PUBLIC_PLATFORM_URL}/user-service`
const LEARNING_SERVICE = `${process.env.NEXT_PUBLIC_PLATFORM_URL}/learning-service`
const PRODUCT_SERVICE = `${process.env.NEXT_PUBLIC_PLATFORM_URL}/product-service`
const LANDING_SERVICE = `${process.env.NEXT_PUBLIC_PLATFORM_URL}/landing-service`

export {
  LANDING_PAGE_URL,
  STORE_PAGE_URL,
  PLATFORM_URL_CLASSROOM,
  PLATFORM_URL_CUSTOMER,
  USER_SERVICE,
  LEARNING_SERVICE,
  PLATFORM_URL,
  PRODUCT_SERVICE,
  LANDING_SERVICE,
}
