---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prod-namespace
  name: deployment-platform-client
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: platform-client
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: platform-client
    spec:
      containers:
      - image: "548364670481.dkr.ecr.us-east-1.amazonaws.com/repoprod:platform-client"
        imagePullPolicy: Always
        name: landing-client
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: prod-namespace
  name: service-platform-client
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: platform-client
